controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\form\LoginForm;
use app\models\form\RegistrationForm;

class AuthController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'registration'],
                        'allow' => true,
                        'roles' => ['?']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Registration action
     *
     * @return type
     */
    public function actionRegistration()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new RegistrationForm();
        if ($model->load(Yii::$app->request->post()) && $model->register()) {
            return $this->goBack();
        }
        return $this->render('registration', [
            'model' => $model,
        ]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\Message;
use yii\data\ActiveDataProvider;
use app\models\form\MessageForm;
use app\models\form\ProfileForm;
use app\models\ContactList;

class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'profile'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                    [
                        'actions' => ['inbox', 'link', 'unlink'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'userDataProvider' => new ActiveDataProvider([
                'query' => User::find()->where(['IS NOT', 'profile_id', null]),
                'pagination' => [
                    'pageSize' => 120
                ]
            ])
        ]);
    }

    /**
     * Displays profile page.
     *
     * @return string
     */
    public function actionProfile($userId = null)
    {
        $user = $userId ? User::findOne($userId) : Yii::$app->user->identity;
        if (!$user) {
            throw new \yii\web\NotFoundHttpException('Can\'t find user');
        }

        $profileForm = new ProfileForm();
        $profileForm->status = $user->profile->status;

        if (Yii::$app->request->isPost && $profileForm->load(Yii::$app->request->post())) {
            if ($profileForm->save()) {
                return $this->refresh();
            }
        }

        return $this->render('profile', [
            'user' => $user,
            'profileForm' => $profileForm
        ]);
    }

    /**
     * Display chats-interface
     *
     * @param type $userId
     * @return type
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionInbox($userId = null)
    {
        $user = Yii::$app->user->identity;
        $contactList = $user->contactList;
        $messageForm = new MessageForm();
        $recipient = null;
        $messages = null;

        if ($userId) {
            $recipient = $this->findUser($userId);
            $messages = Message::getMessageList([$recipient->id, $user->id]);

            if (!$user->inContactList($recipient)) {
                throw new \yii\web\NotFoundHttpException('You can\'t sending messages to this user');
            }

            if (Yii::$app->request->isPost && $messageForm->load(Yii::$app->request->post()) && $messageForm->send($recipient)) {
                return $this->refresh();
            }
        }

        return $this->render('inbox', [
            'contactList' => $contactList,
            'messages' => $messages,
            'recipient' => $recipient,
            'messageForm' => $messageForm
        ]);
    }

    /**
     * adding user to contact list of current user
     *
     * @param integer $userId
     * @return boolean
     */
    public function actionLink($userId)
    {
        ContactList::linkUsers(Yii::$app->user->id, $this->findUser($userId)->id);
        return $this->redirect(\yii\helpers\Url::toRoute(['profile', 'userId' => $userId]));
    }

    /**
     * Delete user from contact list
     *
     * @param integer $userId
     * @return boolean
     */
    public function actionUnlink($userId)
    {
        ContactList::unlinkUsers(Yii::$app->user->id, $this->findUser($userId)->id);
        return $this->redirect(\yii\helpers\Url::toRoute(['profile', 'userId' => $userId]));
    }

    /**
     * finding model of User
     *
     * @param integer $userId
     * @return app\models\User
     * @throws \yii\web\NotFoundHttpException
     */
    private function findUser($userId)
    {
        if ($user = User::findOne($userId)) {
            return $user;
        }

        throw new \yii\web\NotFoundHttpException('User does not exist');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Offline Messenger',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'All Users', 'url' => ['/site/index']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Contact List', 'url' => ['/site/inbox']]
            ) : (
                ['label' => 'Contact List (' . Yii::$app->user->identity->unreadCountAll . ')', 'url' => ['/site/inbox']]
            ),
            ['label' => 'Profile', 'url' => ['/site/profile']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/auth/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/auth/logout'], 'post')
                . Html::submitButton(
                    'Logout',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Offline Messenger <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>