controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\Message;
use yii\data\ActiveDataProvider;
use app\models\form\MessageForm;
use app\models\form\ProfileForm;
use app\models\ContactList;

class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'profile'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                    [
                        'actions' => ['inbox', 'link', 'unlink'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'userDataProvider' => new ActiveDataProvider([
                'query' => User::find()->where(['IS NOT', 'profile_id', null]),
                'pagination' => [
                    'pageSize' => 120
                ]
            ])
        ]);
    }

    /**
     * Displays profile page.
     *
     * @return string
     */
    public function actionProfile($userId = null)
    {
        $user = $userId ? User::findOne($userId) : Yii::$app->user->identity;
        if (!$user) {
            throw new \yii\web\NotFoundHttpException('Can\'t find user');
        }

        $profileForm = new ProfileForm();
        $profileForm->status = $user->profile->status;

        if (Yii::$app->request->isPost && $profileForm->load(Yii::$app->request->post())) {
            if ($profileForm->save()) {
                return $this->refresh();
            }
        }

        return $this->render('profile', [
            'user' => $user,
            'profileForm' => $profileForm
        ]);
    }

    /**
     * Display chats-interface
     *
     * @param type $userId
     * @return type
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionInbox($userId = null)
    {
        $user = Yii::$app->user->identity;
        $contactList = $user->contactList;
        $messageForm = new MessageForm();
        $recipient = null;
        $messages = null;

        if ($userId) {
            $recipient = $this->findUser($userId);
            $messages = Message::getMessageList([$recipient->id, $user->id]);

            if (!$user->inContactList($recipient)) {
                throw new \yii\web\NotFoundHttpException('You can\'t sending messages to this user');
            }

            if (Yii::$app->request->isPost && $messageForm->load(Yii::$app->request->post()) && $messageForm->send($recipient)) {
                return $this->refresh();
            }
        }

        return $this->render('inbox', [
            'contactList' => $contactList,
            'messages' => $messages,
            'recipient' => $recipient,
            'messageForm' => $messageForm
        ]);
    }

    /**
     * adding user to contact list of current user
     *
     * @param integer $userId
     * @return boolean
     */
    public function actionLink($userId)
    {
        ContactList::linkUsers(Yii::$app->user->id, $this->findUser($userId)->id);
        return $this->redirect(\yii\helpers\Url::toRoute(['profile', 'userId' => $userId]));
    }

    /**
     * Delete user from contact list
     *
     * @param integer $userId
     * @return boolean
     */
    public function actionUnlink($userId)
    {
        ContactList::unlinkUsers(Yii::$app->user->id, $this->findUser($userId)->id);
        return $this->redirect(\yii\helpers\Url::toRoute(['profile', 'userId' => $userId]));
    }

    /**
     * finding model of User
     *
     * @param integer $userId
     * @return app\models\User
     * @throws \yii\web\NotFoundHttpException
     */
    private function findUser($userId)
    {
        if ($user = User::findOne($userId)) {
            return $user;
        }

        throw new \yii\web\NotFoundHttpException('User does not exist');
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/inbox.php
<?php

/* @var $this yii\web\View */
/* @var $recipient app\models\User */
/* @var $messageForm app\models\form\MessageForm */

use yii\helpers\Html;

$this->title = 'Inbox';
?>
<div class="site-inbox">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">

        <div class="col-md-3">
            <?=$this->render('inbox/_list', [
                'contactList' => $contactList,
                'recipient' => $recipient
            ])?>
        </div>

        <div class="col-md-9">
            <?=$this->render('inbox/_messages', [
                'messages' => $messages,
                'recipient' => $recipient,
                'messageForm' => $messageForm
            ])?>
        </div>

    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\widgets\ListView;

$this->title = 'Offline Messenger';
?>
<div class="site-index">

<?=ListView::widget([
        'dataProvider' => $userDataProvider,
        'itemView' => 'index/_item'
    ]); ?>

</div>

views/site/profile.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'Profile '.$user->profile->name;
?>
<div class="site-about">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if ($user->id == Yii::$app->user->id) { ?>
        <?php $form = ActiveForm::begin(); ?>
            <?= $form->field($profileForm, 'status')->textInput(['placeholder' => 'Your status']) ?>
            <?= $form->field($profileForm, 'password')->passwordInput() ?>
            <?= $form->field($profileForm, 'password_again')->passwordInput() ?>
            <?= Html::submitButton('Change profile', ['class' => 'btn btn-primary']) ?>
        <?php ActiveForm::end(); ?>
    <?php } else { ?>
        <p><strong>Status: </strong> <?=$user->profile->status ?: '<i>Not setted</i>'?>
        <p>
            <?php if (Yii::$app->user->getId()) { ?>
                <?php if (Yii::$app->user->identity->inContactList($user)) { ?>
                This user already in your contact list <?=Html::a('[delete]', Url::toRoute(['/site/unlink', 'userId' => $user->id]))?>
                <?php } else { ?>
                This user is not in your contact list <?=Html::a('[add]', Url::toRoute(['/site/link', 'userId' => $user->id]))?>
                <?php } ?>
            <?php } ?>
        </p>
    <?php } ?>

</div>